[build]
default_profile = "debug"

[discovery]
file_extensions = ["rs"]
test_patterns = [
    '#\[sheila::test(?:\([^\)]*\))?\]\s*\n\s*(?:pub\s+)?fn\s+(\w+)',
]
suite_patterns = [
    '#\[sheila::suite(?:\([^\)]*\))?\]\s*\n\s*(?:pub\s+)?struct\s+(\w+)',
]
exclude = [
    "target/**",
    "**/.git/**",
    "**/node_modules/**",
]

[reporting]
output_dir = "test-results"
report_formats = ["json", "html", "csv"]
ts_format = "%Y%m%d_%H%M%S"

[runner]
timeout = 30
max_retries = 3

tags = ["api", "external"]

[environments.ci]
timeout = 120
output_dir = "ci-test-results"

[environments.local]
timeout = 30
output_dir = "test-results" 