[build]
incremental = true

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[alias]
ck = "check"
t = "test"
r = "run"
rr = "run --release"
b = "build"
br = "build --release"
